# Generated by Django 4.2.11 on 2026-05-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover photo for this album', null=True, upload_to='albums/covers/'),
        ),
    ]
